src/scheduler/routes/jobs.ts
test/jobs.test.ts

Remove jobs on complete

---

package-lock.json
package.json
src/scheduler/jobs-repo.ts
src/scheduler/routes/jobs.ts
src/scheduler/schemas/jobs/POST/body.json
src/shared/http-job.ts
src/worker/index.ts
test/authenticated_jobs.test.ts
test/jobs.test.ts

Add GET /jobs to retrieve pending jobs

---

client/src/index.ts

Transmit scheduled time as locally-computed delay to work around clock-drift

---

.github/workflows/ci.yml
api/package.json
api/src/scheduler/jobs-repo.ts
api/src/scheduler/schemas/queues/POST/body.json
api/src/shared/http-job.ts
api/test/jobs.test.ts
client/src/index.ts

Add support for Cron Jobs

---

client/package-lock.json
client/package.json
client/src/index.ts
client/test/ms.test.ts

Integrate vercel/ms

---

.github/workflows/ci.yml
api/package-lock.json
api/package.json
api/src/main.ts
api/src/scheduler/basic-auth.ts
api/src/scheduler/index.ts
api/src/scheduler/main.ts
api/src/scheduler/redis.ts
api/src/scheduler/routes/activity.ts
api/src/scheduler/routes/queues.ts
api/src/scheduler/routes/tokens.ts
api/src/scheduler/routes/usage.ts
api/src/scheduler/sentry.ts
api/src/scheduler/telemetry.ts
api/src/scheduler/token-auth.ts
api/src/scheduler/tokens.ts
api/src/shared/telemetrist.ts
api/src/worker/index.ts
api/src/worker/main.ts

Setup sentry

---

api/package.json
client/package-lock.json
client/package.json
client/src/index.ts
client/test/dx.test.ts
client/test/encryption.test.ts
client/test/ms.test.ts
client/test/schema-checks.test.ts

See https://github.com/quirrel-dev/quirrel-next/issues/2.

Add input Validation to @quirrel/client 

---

development-ui/hooks/useQuirrel.tsx
development-ui/package-lock.json
development-ui/package.json
development-ui/pages/pending.tsx
quirrel/generate-proxies.sh
quirrel/package-lock.json
quirrel/src/api/scheduler/queue-repo.ts
quirrel/src/api/scheduler/routes/queues.ts
quirrel/src/api/test/jobs.test.ts

Add "Queue Set"

---

quirrel/src/api/scheduler/token-auth.ts
quirrel/src/api/test/authenticated_jobs.test.ts

For api.quirrel.dev, there are some cases where quirrel.dev impersonates the user (e.g. to recreate incident jobs).
These should count against the quota.
Other admin calls should not count against the quota, as they're not necessarily user-originating.

Don't count all counts against usage quota

---

development-ui/components/EndpointModal.tsx
development-ui/hooks/useQuirrel.tsx
development-ui/lib/encrypted-connection-details.spec.ts
development-ui/lib/encrypted-connection-details.ts
development-ui/lib/hash-config.ts
development-ui/package-lock.json
development-ui/package.json
development-ui/tailwind.config.js

This PR adds support for bookmarking connections to the UI.
It should make production usage of the UI more comfortable.

UI: Allow Bookmarking Connections

---

docs/docs/api/blitz.md
docs/docs/getting-started/blitz-js.md

Docs: Mention Blitz Recipe

---

development-ui/components/Nav.tsx
development-ui/components/SearchBar.tsx
development-ui/components/Table.tsx
development-ui/hooks/useGlobalSearch.tsx
development-ui/lib/search-predicates.ts
development-ui/pages/_app.tsx

Add a Search bar to the Dev UI

---

quirrel/src/api/test/jobs.test.ts
quirrel/src/client/index.ts
quirrel/src/client/test/dx.test.ts

Throw local error on past runAt/delay

---

docs/docs/api/queue.md
quirrel/package-lock.json
quirrel/package.json
quirrel/src/api/scheduler/jobs-repo.ts
quirrel/src/api/scheduler/schemas/queues/POST/body.json
quirrel/src/api/shared/dx-logger.tester.ts
quirrel/src/api/test/activity.test.ts
quirrel/src/api/test/incident.test.ts
quirrel/src/api/test/jobs.test.ts
quirrel/src/api/worker/index.ts
quirrel/src/client/index.ts
quirrel/src/client/job.ts
quirrel/src/client/test/dx.test.ts
quirrel/src/client/test/retry.test.ts

Feature: Retry/Backoff

---

quirrel/package-lock.json
quirrel/package.json
quirrel/src/cli/cron-detector.ts

Fix #94: Ignore node_modules in quirrel ci

---

README.md

A little MarkDown/HTML tidying along with a typo fix.

Fix typo and formatting in README

---

quirrel/package-lock.json
quirrel/package.json
quirrel/src/api/test/jobs.test.ts

190-TimeoutOverflowWarning

---

quirrel/src/api/scheduler/routes/queues.ts
quirrel/src/api/scheduler/schemas/queues/POST/body.json
quirrel/src/api/test/jobs.test.ts
quirrel/src/client/index.ts
quirrel/src/client/test/cron-regex.ts
quirrel/src/shared/is-valid-regex.spec.ts
quirrel/src/shared/is-valid-regex.ts

Let cron-parser check syntax itself

---

quirrel/src/cli/cron-detector.spec.ts
quirrel/src/cli/cron-detector.ts

Detect CronJobs with single-quote imports

---

quirrel/src/client/config.ts
quirrel/src/client/test/dx.test.ts

In non-production mode, prefixed proto should be http

---

development-ui/hooks/useQuirrel.tsx

Heroku disconnects websockets after 30secs. This PR adds a reconnection attempt.

Reconnect on 1006

---

quirrel/generate-proxies.sh

Fixes https://github.com/quirrel-dev/quirrel/pull/388/checks?check_run_id=2606981182

Link client.js to "client/index.js"

---

docs/docs/api/netlify.md
docs/sidebars.js
examples/netlify/.gitignore
examples/netlify/functions/enqueueGreeting.ts
examples/netlify/functions/greetingsQueue.ts
examples/netlify/index.html
examples/netlify/netlify.toml
examples/netlify/package-lock.json
examples/netlify/package.json
quirrel/src/client/config.ts
quirrel/src/netlify.ts

This PR adds `quirrel/netlify`. It's just an alias for the Redwood client, which has exactly the same API as Netlify functions.

Add Netlify Client

---

quirrel/src/api/scheduler/index.ts
quirrel/src/api/test/jobs.test.ts

Don't throw 404 for long Queue endpoints

---

src/cli/commands/ci.test.ts
src/cli/commands/ci.ts
src/cli/commands/detect-cron.ts
src/cli/commands/ui.ts
src/cli/commands/update-cron.ts
src/cli/cron-detector.spec.ts
src/cli/cron-detector.ts

Fix regression where "quirrel ci" didn't actually create any jobs

---

package-lock.json
package.json
src/api/shared/create-redis.ts
src/api/shared/ioredis.d.ts
src/api/shared/usage-meter.ts

Closes #452
My PR to ioredis-mock doesn't seem to get reviewed soon, let's use my fork until it's merged.

Use own ioredis-mock fork until PR is merged

---

package-lock.json

Reverts quirrel-dev/quirrel#688
This broke prod 😓

Revert "Bump dd-trace from 1.1.0 to 1.1.1"

---

src/api/scheduler/jobs-repo.ts
src/api/scheduler/routes/queues.ts
src/api/test/jobs.test.ts

New endpoint to remove all jobs on a queue

---

.github/workflows/ci.yml
src/api/test/jobs.test.ts

Don't test with timezones that observe DST

---

.github/workflows/ci.yml
package-lock.json
package.json

I needed to merge in `main`, which I couldn't do b/c #862 didn't give me edit rights. So here's a replacement PR :)

Update node 17

---

development-ui/src/components/Nav.tsx

This adds additional tailwind classes to the horizontal headbar and the feedback link in the monitoring UI.
Resolves #608

fix: Makes UI Headbar responsive

---

package-lock.json
package.json
src/api/scheduler/index.ts
src/api/test/rate_limit.test.ts

in reaction to today's incident, we're adding rate limiting

add rate limiter

---

src/next.ts

closes #928 
co-authored-by: Jakob Heuser <jakobo@users.noreply.github.com>

fix: add NextAPIHandler type

---

.github/workflows/ci.yml
development-ui/package-lock.json
development-ui/package.json
development-ui/src/lib/encrypted-connection-details.spec.ts
development-ui/src/lib/encrypted-connection-details.ts
development-ui/test/activity.spec.ts
development-ui/test/connection-retry.spec.ts
development-ui/test/deletion.spec.ts
development-ui/test/invoke.spec.ts
development-ui/test/non-standard-port.spec.ts
development-ui/test/playwright.d.ts
development-ui/test/runQuirrel.ts

- use port that's available on macos
- migrate to playwright test runner
- add step to install playwright browsers

chore: migrate to playwright test runner to to fix UI tests

---

.github/workflows/ci.yml
package.json

Reverts quirrel-dev/quirrel#1047

Revert "feat: support node v18"

---

src/cli/commands/index.ts
src/client/config.ts
src/netlify.ts
src/next.ts
src/nuxt.ts
src/redwood.ts
src/remix.ts
src/sveltekit.ts

fix: respect custom host in local dev

---

.github/workflows/ci.yml
package.json

Closes https://github.com/quirrel-dev/quirrel/issues/1129

add node v19 support

---

.github/workflows/ci.yml
package.json

Closes https://github.com/quirrel-dev/quirrel/issues/1149

fix: add node 20 support
